# Generated by Django 2.0.7 on 2018-07-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='featured',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
