# Generated by Django 2.0.7 on 2018-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
